from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1006, 521)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(2000, 2000))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, -358, 484, 2670))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.frame_5 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.t15_visits_popularity = QtWidgets.QPushButton(self.frame_5)
        self.t15_visits_popularity.setObjectName("t15_visits_popularity")
        self.verticalLayout_7.addWidget(self.t15_visits_popularity)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.t15_visits_popularity_from = QtWidgets.QDateEdit(self.frame_5)
        self.t15_visits_popularity_from.setObjectName("t15_visits_popularity_from")
        self.horizontalLayout_11.addWidget(self.t15_visits_popularity_from)
        self.t15_visits_popularity_to = QtWidgets.QDateEdit(self.frame_5)
        self.t15_visits_popularity_to.setObjectName("t15_visits_popularity_to")
        self.horizontalLayout_11.addWidget(self.t15_visits_popularity_to)
        self.verticalLayout_7.addLayout(self.horizontalLayout_11)
        self.gridLayout.addWidget(self.frame_5, 26, 0, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_6.setStyleSheet("\n"
"background-color: rgb(0, 0, 0);")
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout.addWidget(self.line_6, 27, 0, 1, 1)
        self.frame_12 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.t09_workers = QtWidgets.QPushButton(self.frame_12)
        self.t09_workers.setStyleSheet("")
        self.t09_workers.setObjectName("t09_workers")
        self.verticalLayout_13.addWidget(self.t09_workers)
        self.frame_15 = QtWidgets.QFrame(self.frame_12)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_16 = QtWidgets.QLabel(self.frame_15)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_22.addWidget(self.label_16)
        self.t09_workers_id = QtWidgets.QLineEdit(self.frame_15)
        self.t09_workers_id.setObjectName("t09_workers_id")
        self.horizontalLayout_22.addWidget(self.t09_workers_id)
        self.verticalLayout_20.addLayout(self.horizontalLayout_22)
        self.t09_workers_remove = QtWidgets.QPushButton(self.frame_15)
        self.t09_workers_remove.setObjectName("t09_workers_remove")
        self.verticalLayout_20.addWidget(self.t09_workers_remove)
        self.verticalLayout_13.addWidget(self.frame_15)
        self.frame_16 = QtWidgets.QFrame(self.frame_12)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_17 = QtWidgets.QLabel(self.frame_16)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_22.addWidget(self.label_17)
        self.t09_workers_name = QtWidgets.QLineEdit(self.frame_16)
        self.t09_workers_name.setObjectName("t09_workers_name")
        self.verticalLayout_22.addWidget(self.t09_workers_name)
        self.verticalLayout_21.addLayout(self.verticalLayout_22)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_18 = QtWidgets.QLabel(self.frame_16)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_23.addWidget(self.label_18)
        self.t09_workers_sex = QtWidgets.QSpinBox(self.frame_16)
        self.t09_workers_sex.setObjectName("t09_workers_sex")
        self.horizontalLayout_23.addWidget(self.t09_workers_sex)
        self.verticalLayout_21.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_19 = QtWidgets.QLabel(self.frame_16)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_24.addWidget(self.label_19)
        self.t09_workers_spec = QtWidgets.QLineEdit(self.frame_16)
        self.t09_workers_spec.setObjectName("t09_workers_spec")
        self.horizontalLayout_24.addWidget(self.t09_workers_spec)
        self.verticalLayout_21.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_20 = QtWidgets.QLabel(self.frame_16)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_25.addWidget(self.label_20)
        self.t09_workers_birthdate = QtWidgets.QDateEdit(self.frame_16)
        self.t09_workers_birthdate.setObjectName("t09_workers_birthdate")
        self.horizontalLayout_25.addWidget(self.t09_workers_birthdate)
        self.verticalLayout_21.addLayout(self.horizontalLayout_25)
        self.t09_workers_add = QtWidgets.QPushButton(self.frame_16)
        self.t09_workers_add.setObjectName("t09_workers_add")
        self.verticalLayout_21.addWidget(self.t09_workers_add)
        self.verticalLayout_13.addWidget(self.frame_16)
        self.gridLayout.addWidget(self.frame_12, 11, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(1)
        self.frame.setMidLineWidth(0)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.t11_find_worker = QtWidgets.QPushButton(self.frame)
        self.t11_find_worker.setObjectName("t11_find_worker")
        self.verticalLayout_2.addWidget(self.t11_find_worker)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.t11_find_worker_spec_id = QtWidgets.QLineEdit(self.frame)
        self.t11_find_worker_spec_id.setObjectName("t11_find_worker_spec_id")
        self.horizontalLayout_3.addWidget(self.t11_find_worker_spec_id)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.t11_find_worker_from = QtWidgets.QDateEdit(self.frame)
        self.t11_find_worker_from.setObjectName("t11_find_worker_from")
        self.horizontalLayout_2.addWidget(self.t11_find_worker_from)
        self.t11_find_worker_to = QtWidgets.QDateEdit(self.frame)
        self.t11_find_worker_to.setObjectName("t11_find_worker_to")
        self.horizontalLayout_2.addWidget(self.t11_find_worker_to)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.gridLayout.addWidget(self.frame, 15, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.t14_patients_of_worker = QtWidgets.QPushButton(self.frame_4)
        self.t14_patients_of_worker.setObjectName("t14_patients_of_worker")
        self.verticalLayout_6.addWidget(self.t14_patients_of_worker)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_5 = QtWidgets.QLabel(self.frame_4)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_9.addWidget(self.label_5)
        self.t14_patients_of_worker_worker_id = QtWidgets.QLineEdit(self.frame_4)
        self.t14_patients_of_worker_worker_id.setObjectName("t14_patients_of_worker_worker_id")
        self.horizontalLayout_9.addWidget(self.t14_patients_of_worker_worker_id)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.t14_patients_of_worker_from = QtWidgets.QDateEdit(self.frame_4)
        self.t14_patients_of_worker_from.setObjectName("t14_patients_of_worker_from")
        self.horizontalLayout_10.addWidget(self.t14_patients_of_worker_from)
        self.t14_patients_of_worker_to = QtWidgets.QDateEdit(self.frame_4)
        self.t14_patients_of_worker_to.setObjectName("t14_patients_of_worker_to")
        self.horizontalLayout_10.addWidget(self.t14_patients_of_worker_to)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        self.gridLayout.addWidget(self.frame_4, 24, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_3.setStyleSheet("\n"
"background-color: rgb(0, 0, 0);")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 19, 0, 1, 1)
        self.line_10 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_10.setStyleSheet("\n"
"background-color: rgb(0, 0, 0);")
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.gridLayout.addWidget(self.line_10, 8, 0, 1, 1)
        self.frame_7 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.t18_patient_expenses = QtWidgets.QPushButton(self.frame_7)
        self.t18_patient_expenses.setObjectName("t18_patient_expenses")
        self.verticalLayout_8.addWidget(self.t18_patient_expenses)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.t18_patient_expenses_from = QtWidgets.QDateEdit(self.frame_7)
        self.t18_patient_expenses_from.setObjectName("t18_patient_expenses_from")
        self.horizontalLayout_13.addWidget(self.t18_patient_expenses_from)
        self.t18_patient_expenses_to = QtWidgets.QDateEdit(self.frame_7)
        self.t18_patient_expenses_to.setObjectName("t18_patient_expenses_to")
        self.horizontalLayout_13.addWidget(self.t18_patient_expenses_to)
        self.verticalLayout_8.addLayout(self.horizontalLayout_13)
        self.gridLayout.addWidget(self.frame_7, 32, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.t12_reg_visit = QtWidgets.QPushButton(self.frame_2)
        self.t12_reg_visit.setObjectName("t12_reg_visit")
        self.verticalLayout_4.addWidget(self.t12_reg_visit)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.frame_2)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.verticalLayout_4.addWidget(self.dateTimeEdit)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.t12_reg_visit_patient_id = QtWidgets.QLineEdit(self.frame_2)
        self.t12_reg_visit_patient_id.setObjectName("t12_reg_visit_patient_id")
        self.horizontalLayout_6.addWidget(self.t12_reg_visit_patient_id)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.t12_reg_visit_worker_id = QtWidgets.QLineEdit(self.frame_2)
        self.t12_reg_visit_worker_id.setObjectName("t12_reg_visit_worker_id")
        self.horizontalLayout_5.addWidget(self.t12_reg_visit_worker_id)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_18.addWidget(self.label_11)
        self.t12_reg_visit_services_id = QtWidgets.QLineEdit(self.frame_2)
        self.t12_reg_visit_services_id.setObjectName("t12_reg_visit_services_id")
        self.horizontalLayout_18.addWidget(self.t12_reg_visit_services_id)
        self.verticalLayout_4.addLayout(self.horizontalLayout_18)
        self.gridLayout.addWidget(self.frame_2, 17, 0, 2, 1)
        self.line_7 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_7.setStyleSheet("\n"
"background-color: rgb(0, 0, 0);")
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout.addWidget(self.line_7, 29, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_2.setStyleSheet("\n"
"background-color: rgb(0, 0, 0);")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 12, 0, 1, 1)
        self.line_8 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_8.setStyleSheet("\n"
"background-color: rgb(0, 0, 0);")
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout.addWidget(self.line_8, 31, 0, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_5.setStyleSheet("\n"
"background-color: rgb(0, 0, 0);")
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout.addWidget(self.line_5, 25, 0, 1, 1)
        self.frame_8 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.t10_activity = QtWidgets.QPushButton(self.frame_8)
        self.t10_activity.setObjectName("t10_activity")
        self.verticalLayout_14.addWidget(self.t10_activity)
        self.frame_21 = QtWidgets.QFrame(self.frame_8)
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.frame_21)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_7 = QtWidgets.QLabel(self.frame_21)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_30.addWidget(self.label_7)
        self.t10_activity_active_worker_id = QtWidgets.QLineEdit(self.frame_21)
        self.t10_activity_active_worker_id.setObjectName("t10_activity_active_worker_id")
        self.horizontalLayout_30.addWidget(self.t10_activity_active_worker_id)
        self.verticalLayout_25.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_13 = QtWidgets.QLabel(self.frame_21)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_20.addWidget(self.label_13)
        self.t10_activity_date = QtWidgets.QDateEdit(self.frame_21)
        self.t10_activity_date.setObjectName("t10_activity_date")
        self.horizontalLayout_20.addWidget(self.t10_activity_date)
        self.verticalLayout_25.addLayout(self.horizontalLayout_20)
        self.t10_activity_dissmis = QtWidgets.QPushButton(self.frame_21)
        self.t10_activity_dissmis.setObjectName("t10_activity_dissmis")
        self.verticalLayout_25.addWidget(self.t10_activity_dissmis)
        self.t10_activity_inactive = QtWidgets.QPushButton(self.frame_21)
        self.t10_activity_inactive.setObjectName("t10_activity_inactive")
        self.verticalLayout_25.addWidget(self.t10_activity_inactive)
        self.t10_activity_active = QtWidgets.QPushButton(self.frame_21)
        self.t10_activity_active.setObjectName("t10_activity_active")
        self.verticalLayout_25.addWidget(self.t10_activity_active)
        self.verticalLayout_14.addWidget(self.frame_21)
        self.gridLayout.addWidget(self.frame_8, 13, 0, 1, 1)
        self.frame_11 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.t09_spec = QtWidgets.QPushButton(self.frame_11)
        self.t09_spec.setStyleSheet("")
        self.t09_spec.setObjectName("t09_spec")
        self.verticalLayout_12.addWidget(self.t09_spec)
        self.frame_18 = QtWidgets.QFrame(self.frame_11)
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_18)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_15 = QtWidgets.QLabel(self.frame_18)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_21.addWidget(self.label_15)
        self.t09_spec_id = QtWidgets.QLineEdit(self.frame_18)
        self.t09_spec_id.setObjectName("t09_spec_id")
        self.horizontalLayout_21.addWidget(self.t09_spec_id)
        self.verticalLayout_19.addLayout(self.horizontalLayout_21)
        self.t09_spec_remove = QtWidgets.QPushButton(self.frame_18)
        self.t09_spec_remove.setObjectName("t09_spec_remove")
        self.verticalLayout_19.addWidget(self.t09_spec_remove)
        self.verticalLayout_12.addWidget(self.frame_18)
        self.frame_17 = QtWidgets.QFrame(self.frame_11)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_12 = QtWidgets.QLabel(self.frame_17)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_19.addWidget(self.label_12)
        self.t09_spec_description = QtWidgets.QLineEdit(self.frame_17)
        self.t09_spec_description.setObjectName("t09_spec_description")
        self.horizontalLayout_19.addWidget(self.t09_spec_description)
        self.verticalLayout_18.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_21 = QtWidgets.QLabel(self.frame_17)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_26.addWidget(self.label_21)
        self.t09_spec_linked_serv = QtWidgets.QLineEdit(self.frame_17)
        self.t09_spec_linked_serv.setObjectName("t09_spec_linked_serv")
        self.horizontalLayout_26.addWidget(self.t09_spec_linked_serv)
        self.verticalLayout_18.addLayout(self.horizontalLayout_26)
        self.t09_spec_add = QtWidgets.QPushButton(self.frame_17)
        self.t09_spec_add.setObjectName("t09_spec_add")
        self.verticalLayout_18.addWidget(self.t09_spec_add)
        self.verticalLayout_12.addWidget(self.frame_17)
        self.gridLayout.addWidget(self.frame_11, 9, 0, 1, 1)
        self.line_11 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_11.setStyleSheet("\n"
"background-color: rgb(0, 0, 0);")
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.gridLayout.addWidget(self.line_11, 14, 0, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_4.setStyleSheet("\n"
"background-color: rgb(0, 0, 0);")
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 23, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line.setToolTipDuration(5)
        self.line.setStyleSheet("\n"
"background-color: rgb(0, 0, 0);")
        self.line.setLineWidth(5)
        self.line.setMidLineWidth(5)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 16, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.t13_workers_of_patient = QtWidgets.QPushButton(self.frame_3)
        self.t13_workers_of_patient.setObjectName("t13_workers_of_patient")
        self.verticalLayout_5.addWidget(self.t13_workers_of_patient)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_7.addWidget(self.label_4)
        self.t13_workers_of_patient_patient_id = QtWidgets.QLineEdit(self.frame_3)
        self.t13_workers_of_patient_patient_id.setObjectName("t13_workers_of_patient_patient_id")
        self.horizontalLayout_7.addWidget(self.t13_workers_of_patient_patient_id)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.t13_workers_of_patient_from = QtWidgets.QDateEdit(self.frame_3)
        self.t13_workers_of_patient_from.setObjectName("t13_workers_of_patient_from")
        self.horizontalLayout_8.addWidget(self.t13_workers_of_patient_from)
        self.t13_workers_of_patient_to = QtWidgets.QDateEdit(self.frame_3)
        self.t13_workers_of_patient_to.setObjectName("t13_workers_of_patient_to")
        self.horizontalLayout_8.addWidget(self.t13_workers_of_patient_to)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.gridLayout.addWidget(self.frame_3, 20, 0, 1, 1)
        self.line_9 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_9.setStyleSheet("\n"
"background-color: rgb(0, 0, 0);")
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.gridLayout.addWidget(self.line_9, 10, 0, 1, 1)
        self.t16_visit_coast = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.t16_visit_coast.setObjectName("t16_visit_coast")
        self.gridLayout.addWidget(self.t16_visit_coast, 28, 0, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.t17_workers_salary = QtWidgets.QPushButton(self.frame_6)
        self.t17_workers_salary.setObjectName("t17_workers_salary")
        self.verticalLayout_9.addWidget(self.t17_workers_salary)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.t17_workers_salary_from = QtWidgets.QDateEdit(self.frame_6)
        self.t17_workers_salary_from.setObjectName("t17_workers_salary_from")
        self.horizontalLayout_12.addWidget(self.t17_workers_salary_from)
        self.t17_workers_salary_to = QtWidgets.QDateEdit(self.frame_6)
        self.t17_workers_salary_to.setObjectName("t17_workers_salary_to")
        self.horizontalLayout_12.addWidget(self.t17_workers_salary_to)
        self.verticalLayout_9.addLayout(self.horizontalLayout_12)
        self.gridLayout.addWidget(self.frame_6, 30, 0, 1, 1)
        self.line_12 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_12.setStyleSheet("\n"
"background-color: rgb(0, 0, 0);")
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.gridLayout.addWidget(self.line_12, 4, 0, 1, 1)
        self.frame_9 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_20 = QtWidgets.QFrame(self.frame_9)
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.frame_20)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.t09_services = QtWidgets.QPushButton(self.frame_20)
        self.t09_services.setObjectName("t09_services")
        self.verticalLayout_24.addWidget(self.t09_services)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_24 = QtWidgets.QLabel(self.frame_20)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_29.addWidget(self.label_24)
        self.t09_services_id = QtWidgets.QLineEdit(self.frame_20)
        self.t09_services_id.setObjectName("t09_services_id")
        self.horizontalLayout_29.addWidget(self.t09_services_id)
        self.verticalLayout_24.addLayout(self.horizontalLayout_29)
        self.t09_services_remove = QtWidgets.QPushButton(self.frame_20)
        self.t09_services_remove.setObjectName("t09_services_remove")
        self.verticalLayout_24.addWidget(self.t09_services_remove)
        self.verticalLayout_10.addWidget(self.frame_20)
        self.frame_19 = QtWidgets.QFrame(self.frame_9)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.frame_19)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_22 = QtWidgets.QLabel(self.frame_19)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_27.addWidget(self.label_22)
        self.t09_services_description = QtWidgets.QLineEdit(self.frame_19)
        self.t09_services_description.setObjectName("t09_services_description")
        self.horizontalLayout_27.addWidget(self.t09_services_description)
        self.verticalLayout_23.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label_25 = QtWidgets.QLabel(self.frame_19)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_31.addWidget(self.label_25)
        self.t09_services_price = QtWidgets.QLineEdit(self.frame_19)
        self.t09_services_price.setObjectName("t09_services_price")
        self.horizontalLayout_31.addWidget(self.t09_services_price)
        self.verticalLayout_23.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_23 = QtWidgets.QLabel(self.frame_19)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_28.addWidget(self.label_23)
        self.t09_services_linked_spec = QtWidgets.QLineEdit(self.frame_19)
        self.t09_services_linked_spec.setObjectName("t09_services_linked_spec")
        self.horizontalLayout_28.addWidget(self.t09_services_linked_spec)
        self.verticalLayout_23.addLayout(self.horizontalLayout_28)
        self.t09_services_add = QtWidgets.QPushButton(self.frame_19)
        self.t09_services_add.setObjectName("t09_services_add")
        self.verticalLayout_23.addWidget(self.t09_services_add)
        self.verticalLayout_10.addWidget(self.frame_19)
        self.gridLayout.addWidget(self.frame_9, 5, 0, 1, 1)
        self.frame_10 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.t09_patients = QtWidgets.QPushButton(self.frame_10)
        self.t09_patients.setObjectName("t09_patients")
        self.verticalLayout_11.addWidget(self.t09_patients)
        self.frame_13 = QtWidgets.QFrame(self.frame_10)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_6 = QtWidgets.QLabel(self.frame_13)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_14.addWidget(self.label_6)
        self.t09_patient_id = QtWidgets.QLineEdit(self.frame_13)
        self.t09_patient_id.setObjectName("t09_patient_id")
        self.horizontalLayout_14.addWidget(self.t09_patient_id)
        self.verticalLayout_15.addLayout(self.horizontalLayout_14)
        self.t09_patient_remove = QtWidgets.QPushButton(self.frame_13)
        self.t09_patient_remove.setObjectName("t09_patient_remove")
        self.verticalLayout_15.addWidget(self.t09_patient_remove)
        self.verticalLayout_11.addWidget(self.frame_13)
        self.frame_14 = QtWidgets.QFrame(self.frame_10)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.Labelt09_patient_name = QtWidgets.QLabel(self.frame_14)
        self.Labelt09_patient_name.setObjectName("Labelt09_patient_name")
        self.verticalLayout_16.addWidget(self.Labelt09_patient_name)
        self.t09_patient_name = QtWidgets.QLineEdit(self.frame_14)
        self.t09_patient_name.setObjectName("t09_patient_name")
        self.verticalLayout_16.addWidget(self.t09_patient_name)
        self.verticalLayout_17.addLayout(self.verticalLayout_16)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.t09label = QtWidgets.QLabel(self.frame_14)
        self.t09label.setObjectName("t09label")
        self.horizontalLayout_15.addWidget(self.t09label)
        self.t09_patient_sex = QtWidgets.QSpinBox(self.frame_14)
        self.t09_patient_sex.setObjectName("t09_patient_sex")
        self.horizontalLayout_15.addWidget(self.t09_patient_sex)
        self.verticalLayout_17.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_9 = QtWidgets.QLabel(self.frame_14)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_16.addWidget(self.label_9)
        self.t09_patient_medicalid = QtWidgets.QLineEdit(self.frame_14)
        self.t09_patient_medicalid.setObjectName("t09_patient_medicalid")
        self.horizontalLayout_16.addWidget(self.t09_patient_medicalid)
        self.verticalLayout_17.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_10 = QtWidgets.QLabel(self.frame_14)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_17.addWidget(self.label_10)
        self.t09_patient_birthdate = QtWidgets.QDateEdit(self.frame_14)
        self.t09_patient_birthdate.setObjectName("t09_patient_birthdate")
        self.horizontalLayout_17.addWidget(self.t09_patient_birthdate)
        self.verticalLayout_17.addLayout(self.horizontalLayout_17)
        self.t09_patient_add = QtWidgets.QPushButton(self.frame_14)
        self.t09_patient_add.setObjectName("t09_patient_add")
        self.verticalLayout_17.addWidget(self.t09_patient_add)
        self.verticalLayout_11.addWidget(self.frame_14)
        self.gridLayout.addWidget(self.frame_10, 3, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 1, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayout.addWidget(self.scrollArea)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.table = QtWidgets.QTableView(self.centralwidget)
        self.table.setObjectName("table")
        self.verticalLayout.addWidget(self.table)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.t15_visits_popularity.setText(_translate("MainWindow", "популярность услуг"))
        self.t09_workers.setText(_translate("MainWindow", "сотрудники"))
        self.label_16.setText(_translate("MainWindow", "id врача:"))
        self.t09_workers_remove.setText(_translate("MainWindow", "Удалить врача"))
        self.label_17.setText(_translate("MainWindow", "ФИО"))
        self.label_18.setText(_translate("MainWindow", "Пол"))
        self.label_19.setText(_translate("MainWindow", "Специализация(id)"))
        self.label_20.setText(_translate("MainWindow", "Дата рождения"))
        self.t09_workers_add.setText(_translate("MainWindow", "Добавить работника"))
        self.t11_find_worker.setText(_translate("MainWindow", "поиск свободного врача со специальностью"))
        self.label.setText(_translate("MainWindow", "специальность(id):"))
        self.t14_patients_of_worker.setText(_translate("MainWindow", "пациенты принимающиеся у рабочего"))
        self.label_5.setText(_translate("MainWindow", "id врача:"))
        self.t18_patient_expenses.setText(_translate("MainWindow", "сумма затраченая пациентом за промежуток"))
        self.t12_reg_visit.setText(_translate("MainWindow", "регистрация приема + услуги"))
        self.label_3.setText(_translate("MainWindow", "id пациента:"))
        self.label_2.setText(_translate("MainWindow", "id врача:"))
        self.label_11.setText(_translate("MainWindow", "id услуг:"))
        self.t10_activity.setText(_translate("MainWindow", "активность сотрудников"))
        self.label_7.setText(_translate("MainWindow", "id  сотрудника:"))
        self.label_13.setText(_translate("MainWindow", "Дата:"))
        self.t10_activity_dissmis.setText(_translate("MainWindow", "Уволить"))
        self.t10_activity_inactive.setText(_translate("MainWindow", "Отправить в отпуск"))
        self.t10_activity_active.setText(_translate("MainWindow", "Вернуть с отпуска"))
        self.t09_spec.setText(_translate("MainWindow", "специализации"))
        self.label_15.setText(_translate("MainWindow", "id специализации:"))
        self.t09_spec_remove.setText(_translate("MainWindow", "Удалить cпециализацию"))
        self.label_12.setText(_translate("MainWindow", "описание:"))
        self.label_21.setText(_translate("MainWindow", "связанные услги(id):"))
        self.t09_spec_add.setText(_translate("MainWindow", "Добавить cпециализацию"))
        self.t13_workers_of_patient.setText(_translate("MainWindow", "врачи пациента за промежуток времени"))
        self.label_4.setText(_translate("MainWindow", "id пациента:"))
        self.t16_visit_coast.setText(_translate("MainWindow", "стоимость приема"))
        self.t17_workers_salary.setText(_translate("MainWindow", "начисление зарплат за промежуток"))
        self.t09_services.setText(_translate("MainWindow", "услуги"))
        self.label_24.setText(_translate("MainWindow", "id услуги:"))
        self.t09_services_remove.setText(_translate("MainWindow", "Удалить услугу"))
        self.label_22.setText(_translate("MainWindow", "описание:"))
        self.label_25.setText(_translate("MainWindow", "Цена:"))
        self.label_23.setText(_translate("MainWindow", "связанные специализции(id):"))
        self.t09_services_add.setText(_translate("MainWindow", "Добавить услугу"))
        self.t09_patients.setText(_translate("MainWindow", "пациенты"))
        self.label_6.setText(_translate("MainWindow", "id пациента:"))
        self.t09_patient_remove.setText(_translate("MainWindow", "Удалить пациента"))
        self.Labelt09_patient_name.setText(_translate("MainWindow", "ФИО"))
        self.t09label.setText(_translate("MainWindow", "Пол"))
        self.label_9.setText(_translate("MainWindow", "Медкарта"))
        self.label_10.setText(_translate("MainWindow", "Дата рождения"))
        self.t09_patient_add.setText(_translate("MainWindow", "Добавить пациента"))


